### ISSUE TITLE
Accessing Attendance module not possible in superuser mode

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#108]
If I enable the superuser-mode to access the custom dashboards, I cannot access the attendance module anymore:

```
2024-02-19 12:57:23,221 1 ERROR odoo-time odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5231, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 921, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1324, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 465, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 438, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/verdigado_attendance/models/res_users.py", line 11, in get_effective_holiday_overtime_factor
    return self.env.user.employee_id._get_effective_holiday_overtime_factor()
  File "/mnt/extra-addons/verdigado_attendance/models/hr_employee.py", line 30, in _get_effective_holiday_overtime_factor
    self.ensure_one()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5234, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: hr.employee(
```

**Comment by albig** [comment]
I think, it's not related to the super user "OdooBot" itself. It seems to happen with users without related employee record. This may happen with manager accounts, not using Odoo itself for time tracking.
