### ISSUE TITLE
Personalisierter ical_link "My team leaves" hat kein Zugriff auf  Mitarbeiter-Namen 

### ISSUE THREAD

**Issue by albig** [verdigado/odoo-customize#70]
Beim Aufruf erhält man nur einen 500er-Server error. Im Log findet sich die Antwort:

```
2023-11-27 12:59:28,474 975792 ERROR demo werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/api.py", line 891, in get
return field_cache[record._ids[0]]
KeyError: 86

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1082, in __get__
value = env.cache.get(record, self)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 894, in get
raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'hr.employee(86,).name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1108, in __get__
recs._fetch_field(self)
File "/usr/lib/python3/dist-packages/odoo/models.py", line 3285, in _fetch_field
self._read(fnames)
File "/usr/lib/python3/dist-packages/odoo/addons/hr/models/hr_employee.py", line 168, in _read
return super(HrEmployeePrivate, self)._read(fields)
File "/usr/lib/python3/dist-packages/odoo/models.py", line 3405, in _read
raise self.env['ir.rule']._make_access_error('read', forbidden)
odoo.exceptions.AccessError: Aufgrund von Sicherheitsbestimmungen ist es Ihnen nicht gestattet, Datensätze des Typs „Mitarbeiter“ (hr.employee) einzusehen.

Wenden Sie sich gegebenenfalls an Ihren Administrator, um den Zugang zu beantragen.
```

**Comment by hbrunn** [comment]
das liest sich als ob der User keinen Zugriff auf die Employees des Teams hat, ist das so gedacht?

Falls ja, ist die Lösung `record.sudo().employee_id.name`, anderfalls müssen wir schauen was hier verkehrt ist (entweder sieht der Mitarbeiter leaves die er nicht sehen sollte, oder hat keinen Zugriff auf den Namen des Mitarbeiters)

**Comment by albig** [comment]
Sudo hilft mit `record.sudo().employee_id.name`. 

Das Problem tauch bei einem Personalveranwortlichen auf. Mit der Domain `[]` kann er ja dann im ical-Export alle Mitarbeitenden "sehen".

Ein normaler Mitarbeiter hat nur sich im Export. Auch nicht die anderen Team-Mitglieder.

**Comment by hbrunn** [comment]
also setze ich das sudo in die Daten und alles ist gut?

**Comment by albig** [comment]
Können wir gleich mal drüber diskutieren. Das sudo() aber auf jeden Fall.

**Comment by hbrunn** [comment]
@albig hier wolltest Du noch schauen ob die betroffenen Mitarbeiter auch in Odoo mehr Abwesenheiten sehen als sie sollten
